### ISSUE TITLE
模型文件写死导致Visual Studio下build目录有误 / VS下编译的低帧数

### ISSUE THREAD

**Issue by Plusle** [SunXLei/SRender#1]
您好，首先感谢您提供的宝贵的实战参考，有几个问题想请教一下

一个不太重要的问题，如题所述，因为msbuild会把文件编译后放在build/Debug下所以默认情况下反而会找不到模型文件。或许加个命令行参数让他接收一下目录位置也好。当然这个项目的前提下，可能这个也不是很重要。

另外想知道您是用什么环境开发的，CLion、VS或者说其他的工具。我注意到在VS下编译的程序帧数比我用MinGW编译的要低20帧以上，所以感觉您在调试的时候大概至少不是用的VC的编译器（提供的二进制文件以及我在VS下编译的文件表现相同，VS在程序刚启动的镜头距离下帧数大概是5帧，而MinGW的是28帧左右。近距离观察的情况下VS的版本只有1帧甚至都不到，而MinGW依然可以保持5到8帧左右）。导致这个巨大的帧数差有什么明确的原因吗？

最后有个额外的问题想请教，因为图形api包括winapi相关的工程我之前都在VS下构建的，想尝试cmake管理项目但是碰到些阻碍。比如自己写OpenGL的时候用的GLFW、或者之前看的软渲器[项目](https://github.com/skywind3000/mini3d)的时候，涉及winapi调用的话似乎有几个动态链接库是需要链接的，VS创建的项目都会自动在Linker->Input添加user32,gdi32和shell32几个库，但是换编译器的话就不太清楚怎么写了。我没有找到您项目里牵扯这方面的设定，cmake生成VS工程是自动引入那几个库的，但生成makefile的话似乎就没有相关的设定，但结果依然可以正常调用而不牵扯任何undefined reference的问题。可以麻烦您讲解下具体原理或者提供一些相关文档吗。

**Comment by SunXLei** [comment]
同学你好，感谢来信！


关于目录不正确的问题，我这里用cmakefile生成VS工程文件，或者直接用clion打开，在IDE里面直接运行应该是可以的，如果运行编译之后的exe文件的话确实目录会不正确，当时没考虑太多，确实可以加一个命令行参数来解决，另外我是用VS开发的。


关于MINGW和MSVC编译器下的帧数差距，这个我当时其实也很疑惑，找了一些资料也没有解决，所以暂时就搁置了。可能是不同编译器在开启不同的编译优化选项之后，优化的方式有所不同，或者说MSVC还有一些其他的编译优化选项没有开启，才导致了这种巨大的帧数差异？都有可能吧。


最后关于dll的问题，我今早查了查编译过程，在Clion里用MINGW进行编译的时候其实最后还是用的g++，在调用g++的时候编译器会自动默认帮我们 -l 这几个库。所以不用像在VS里面那样写出来。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunXLei/SRender"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 凌晨4:37
收件人:&nbsp;"SunXLei/SRender"<SRender@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[SunXLei/SRender] 模型文件写死导致Visual Studio下build目录有误 / VS下编译的低帧数 (#1)





 
一个不太重要的问题，如题所述，因为msbuild会把文件编译后放在build/Debug下所以默认情况下反而会找不到模型文件。或许加个命令行参数让他接收一下目录位置也好。当然这个项目的前提下，可能这个也不是很重要。
 
另外想知道您是用什么环境开发的，CLion、VS或者说其他的工具。我注意到在VS下编译的程序帧数比我用MinGW编译的要低20帧以上，所以感觉您在调试的时候大概至少不是用的VC的编译器（提供的二进制文件以及我在VS下编译的文件表现相同，VS在程序刚启动的镜头距离下帧数大概是5帧，而MinGW的是28帧左右。近距离观察的情况下VS的版本只有1帧甚至都不到，而MinGW依然可以保持5到8帧左右）。导致这个巨大的帧数差有什么明确的原因吗？
 
最后有个额外的问题想请教，因为图形api包括winapi相关的工程我之前都在VS下构建的，想尝试cmake管理项目但是碰到些阻碍。比如自己写OpenGL的时候用的GLFW、或者之前看的软渲器项目的时候，涉及winapi调用的话似乎有几个动态链接库是需要链接的，VS创建的项目都会自动在Linker-&gt;Input添加user32,gdi32和shell32几个库，但是换编译器的话就不太清楚怎么写了。我没有找到您项目里牵扯这方面的设定，cmake生成VS工程是自动引入那几个库的，但生成makefile的话似乎就没有相关的设定，但结果依然可以正常调用而不牵扯任何undefined reference的问题。可以麻烦您讲解下具体原理或者提供一些相关文档吗。

**Comment by SunXLei** [comment]
同学你好！

关于目录不正确的问题，我这里用cmakefile生成VS工程文件，或者直接用clion打开，在IDE里面直接运行应该是可以的，如果运行编译之后的exe文件的话确实目录会不正确，当时没考虑太多，确实可以加一个命令行参数来解决，另外我是用VS开发的。

关于MINGW和MSVC编译器下的帧数差距，这个我当时其实也很疑惑，找了一些资料也没有解决，所以暂时就搁置了。可能是不同编译器在开启不同的编译优化选项之后，优化的方式有所不同，或者说MSVC还有一些其他的编译优化选项没有开启，才导致了这种巨大的帧数差异？都有可能吧。

最后关于dll的问题，我今早查了查编译过程，在Clion里用MINGW进行编译的时候其实最后还是用的g++，在调用g++的时候编译器会自动默认帮我们 -l 这几个库。所以不用像在VS里面那样写出来。

**Comment by SunXLei** [comment]
同学你好！

关于目录不正确的问题，我这里用cmakefile生成VS工程文件，或者直接用clion打开，在IDE里面直接运行应该是可以的，如果运行编译之后的exe文件的话确实目录会不正确，当时没考虑太多，确实可以加一个命令行参数来解决，另外我是用VS开发的。

关于MINGW和MSVC编译器下的帧数差距，这个我当时其实也很疑惑，找了一些资料也没有解决，所以暂时就搁置了。可能是不同编译器在开启不同的编译优化选项之后，优化的方式有所不同，或者说MSVC还有一些其他的编译优化选项没有开启，才导致了这种巨大的帧数差异？都有可能吧。

最后关于dll的问题，我今早查了查编译过程，在Clion里用MINGW进行编译的时候其实最后还是用的g++，在调用g++的时候编译器会自动默认帮我们 -l 这几个库。所以不用像在VS里面那样写出来。

**Comment by Plusle** [comment]
您好，感谢回复

测试了一下用cmake生成的工程文件打开，的确可以正确加载模型了。之前并没有去看代码里是怎么设置文件路径的，用msbuild在命令行编译了之后手动打开了编译完的build/Debug目录下的exe文件所以造成了这个区别。所以VS是在工程目录原点运行的`.Debug/SRender.exe`，所以可以在`..`下找到obj文件夹，看来单纯是VS自己挖了个坑然后自己爬上来了。

另外关于链接的问题，想知道您所说的“查看编译过程”所看的是哪里。刚才试着对比了一下几个项目构建的cmake文件，确实看到build/CMakeFiles/SRender.dir/linklibs.rsp文件下写了`-l`参数链接的库，也看到了build/CMakeFiles/version/CMakeCCompiler.cmake里面在最后有一个CMAKE_<LANG>_IMPLICIT_LINK_LIBRARIES这么一个参数指定了默认链接的库，一知半解得大概能想象它是怎么关联上这些东西的了。只是不知道您是不是有其他的方法能看到流程层面更清晰的东西。

之前自己想写软渲的时候以及学opengl的时候的想写的项目但凡想要脱离VS都要碰到点cmake配置问题然后撞一脑袋包，又怕在莫名的问题上越陷越深只好灰头土脸回去继续VS了。所以，虽然确实很不好意思在软渲的项目底下问了一堆winapi的问题，但还希望您多指教。

**Comment by SunXLei** [comment]
用gcc xxx.c -o xxx.exe -v 可以查看更多的细节，windows下的MinGW会默认链接这几个库-lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -liconv -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt。

另外，如果用cmake生成makefile，有一个cmakecache.txt的文件里有这么一行：
//Libraries linked by default with all C++ applications.
CMAKE_CXX_STANDARD_LIBRARIES:STRING=-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
这里应该是把user, gdi, shell都给链接上去了

**Comment by Plusle** [comment]
感谢，大概明白了该去看什么位置的东西了
